ChickenLive/final_repo_test/final_repo_test/Areas/Account/Controllers/Account_HomeController.cs
using ClassLibrary;
using ClassLibrary.Models;
using ClassLibrary.ViewModels.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace final_repo_test.Areas.Account.Controllers
{
    [Area("Account")]
    public class Account_HomeController : Controller
    {
        //下面三行要用DBcontext要創的
        private readonly ChickenDbContext applicationDbContext;

        public Account_HomeController(ChickenDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }
        //這邊以上
        [HttpGet]
        
        public async Task<IActionResult> Index()
        {
            var accounts = await applicationDbContext.Accounts.ToListAsync();
            return View(accounts);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddVM addAccountRequest)
        {
            var account = new UserAccount()
            {
                A_Name = addAccountRequest.A_Name,
                UserName = addAccountRequest.UserName,
                UserPWD = addAccountRequest.UserPWD,
                A_Gender = addAccountRequest.A_Gender,
                Birthday = addAccountRequest.Birthday,
                A_level = addAccountRequest.A_level,
                A_Email = addAccountRequest.A_Email,
                A_Phone = addAccountRequest.A_Phone,
                A_add = addAccountRequest.A_add,
                A_RegisteredAt = addAccountRequest.A_RegisteredAt,
                A_NickName = addAccountRequest.A_NickName,
                A_Coin = addAccountRequest.A_Coin,
                P_id = addAccountRequest.P_id,


            };
            await applicationDbContext.Accounts.AddAsync(account);
            await applicationDbContext.SaveChangesAsync();

            return RedirectToAction("Index");


        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? A_Id)
        {
            //if (A_Id == null)
            //{
            //    return RedirectToAction("Add");
            //}
            var account = await applicationDbContext.Accounts.FirstOrDefaultAsync(x => x.A_ID == A_Id);
            if (account != null)
            {
                var viewModel = new Edit()
                {
                    A_ID = account.A_ID,
                    A_Name = account.A_Name,
                    UserName = account.UserName,
                    UserPWD = account.UserPWD,
                    A_Gender = account.A_Gender,
                    Birthday = account.Birthday,
                    A_level = account.A_level,
                    A_Email = account.A_Email,
                    A_Phone = account.A_Phone,
                    A_add = account.A_add,
                    A_RegisteredAt = account.A_RegisteredAt,
                    A_NickName = account.A_NickName,
                    A_Coin = account.A_Coin,
                    P_id = account.P_id,
                };
                return await Task.Run(() => View("Edit", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Edit edit)
        {
            var account = await applicationDbContext.Accounts.FindAsync(edit.A_ID);
            if (account != null)
            {
                account.A_ID = edit.A_ID;
                account.A_Name = edit.A_Name;
                account.UserName = edit.UserName;
                account.UserPWD = edit.UserPWD;
                //account.PasswordHash = edit.UserPWD;
                account.A_Gender = edit.A_Gender;
                account.Birthday = edit.Birthday;
                account.A_level = edit.A_level;
                account.A_Email = edit.A_Email;
                account.A_Phone = edit.A_Phone;
                account.A_add = edit.A_add;
                account.A_RegisteredAt = edit.A_RegisteredAt;
                account.A_NickName = edit.A_NickName;
                account.A_Coin = edit.A_Coin;
                account.P_id = edit.P_id;

                await applicationDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Edit edit)
        {
            var account  = await applicationDbContext.Accounts.FindAsync(edit.A_ID);
            if (account != null) 
            {
                applicationDbContext.Accounts.Remove(account);
                await applicationDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ChickenLive/final_repo_test/final_repo_test/Areas/Account/Views/Account_Home/Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ClassLibrary.ViewModels.Account.AddVM
@using ClassLibrary.Enum

@{
    ViewData["Title"] = "Add Account";
    Layout = "_Layout";

}
@section Styles{
    <link href="~/css/AccountStyle/addstyle.css" rel="stylesheet" />
    
}

<body>
    <div class="container">
        <div class="title">新增會員</div>
        <div class="content">
            <form method="post" action="Add">
                <div class="user-details">
                   @* <div class="input-box">
                        <span class="details">ID</span>
                        <input type="text" placeholder="1" required asp-for="A_ID">
                    </div>*@
                    <div class="input-box">
                        <span class="details">權限</span>
                        <input type="text" placeholder="Normal" value="1" required asp-for="A_level">
                    </div>
                    <div class="input-box">
                        <span class="details">全名</span>
                        <input type="text" placeholder="Enter your name" value="Iren" required asp-for="A_Name">
                        <span asp-validation-for="A_Name" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">暱稱</span>
                        <input type="text" placeholder="Enter your NickName" value="Iren" required asp-for="A_NickName">
                        <span asp-validation-for="A_NickName" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">使用者名稱</span>
                        <input type="text" placeholder="Enter your username" value="Iren" required asp-for="UserName">
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">Email</span>
                        <input type="text" placeholder="Enter your email" value="Iren@gmail.com" required asp-for="A_Email">
                        <span asp-validation-for="A_Email" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">密碼</span>
                        <input type="password" placeholder="Enter your password" value="user123" required asp-for="UserPWD">
                        <span asp-validation-for="UserPWD" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">電話號碼</span>
                        <input type="text" placeholder="Enter your number" value="0933915786" required asp-for="A_Phone">
                        <span asp-validation-for="A_Phone" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="birthday">生日</span>
                        <input type="date" id="birthday" name="birthday" value="1990-01-01" asp-for="Birthday">
                    </div>
                    <div class="input-box">
                        <span class="details">地址</span>
                        <input type="text" placeholder="Enter your address" value="高雄市前金區" required asp-for="A_add">
                        <span asp-validation-for="A_add" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">Coin</span>
                        <input type="text" placeholder="Coin" value="1000" required asp-for="A_Coin">
                       
                    </div>
                    <div class="input-box">
                        <span class="Registered">註冊日期</span>
                        <input type="date" id="Registered" name="Registered" value="2023-04-27" asp-for="A_RegisteredAt">
                    </div>
                    <div class="input-box">
                        <span class="details">裝備</span>
                        <input type="text" placeholder="給他一件裝備" value="1" required asp-for="P_id">
                        @*<select asp-for="P_id" placeholder="給他一件裝備" required>
                            <option value="1">反摺袖襯衫</option>
                            <option value="2">短袖襯衫</option>
                        </select>*@
                    </div>
                </div>
                <div class="gender-details">
                    <div class="gender-details">
                        <input type="radio" asp-for="A_Gender" id="dot-1" value="@((int)Gender.男)" checked="@((Model?.A_Gender == Gender.男) ? "checked" : null)">
                        <input type="radio" asp-for="A_Gender" id="dot-2" value="@((int)Gender.女)" checked="@((Model?.A_Gender == Gender.女) ? "checked" : null)">
                        <input type="radio" asp-for="A_Gender" id="dot-3" value="@((int)Gender.其他)" checked="@((Model?.A_Gender == Gender.其他) ? "checked" : null)">

                        <span class="gender-title">性別</span>
                        <span asp-validation-for="A_Gender" class="text-danger"></span>
                    <div class="category">
                        <label for="dot-1">
                            <span class="dot one"></span>
                            <span class="gender">男性</span>
                        </label>
                        <label for="dot-2">
                            <span class="dot two"></span>
                            <span class="gender">女性</span>
                        </label>
                        <label for="dot-3">
                            <span class="dot three"></span>
                            <span class="gender">不方便透漏</span>
                        </label>
                    </div>
                </div>
                <div class="button">
                    <input type="submit" value="儲存">
                </div>
                <a asp-area="Account" asp-controller="Account_Home" asp-action="Index" asp-route-id="" class="btn"><i class=" fa fa-sharp fa-solid fa-arrow-left"></i>回上一頁</a>
            </form>
        </div>
    </div>

</body>

@section Script{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ChickenLive/final_repo_test/final_repo_test/Areas/Account/Views/Account_Home/Class.cshtml
namespace final_repo_test.Areas.Account.Views.Account_Home
{
    public class Class
    {
    }
}

ChickenLive/final_repo_test/final_repo_test/Areas/Account/Views/Account_Home/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ClassLibrary.ViewModels.Account.Edit
@using ClassLibrary.Enum
@{
    ViewData["Title"] = "Edit Account";
    Layout = "_Layout";

}
@section Styles{
    <link href="~/css/AccountStyle/editstyle.css" rel="stylesheet" />
}
<body>
    <div class="container">
        <div class="title">編輯會員</div>
        <div class="content">
            <form method="post" action="Edit">
                <div class="user-details">
                     <div class="input-box">
                    <span class="details">ID</span>
                    <input type="text" placeholder="ID" required asp-for="A_ID" readonly>
                    </div>
                    <div class="input-box">
                        <span class="details">權限</span>
                        <input type="text" placeholder="Enter Level" required asp-for="A_level">
                    </div>
                    <div class="input-box">
                        <span class="details">全名</span>
                        <input type="text" placeholder="Enter your name" required asp-for="A_Name">
                        <span asp-validation-for="A_Name" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">暱稱</span>
                        <input type="text" placeholder="Enter your NickName" required asp-for="A_NickName">
                        <span asp-validation-for="A_NickName" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">使用者名稱</span>
                        <input type="text" placeholder="Enter your username" required asp-for="UserName">
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">Email</span>
                        <input type="text" placeholder="Enter your email" required asp-for="A_Email">
                        <span asp-validation-for="A_Email" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">密碼</span>
                        <input type="text" placeholder="Enter your password" required asp-for="UserPWD">
                        <span asp-validation-for="UserPWD" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">電話號碼</span>
                        <input type="text" placeholder="Enter your number" required asp-for="A_Phone">
                        <span asp-validation-for="A_Phone" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="birthday">生日</span>
                        <input type="date" id="birthday" name="birthday" value="1990-01-01" asp-for="Birthday">
                    </div>
                    <div class="input-box">
                        <span class="details">地址</span>
                        <input type="text" placeholder="Enter your address" required asp-for="A_add">
                        <span asp-validation-for="A_add" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <span class="details">Coin</span>
                        <input type="text" placeholder="Coin" required asp-for="A_Coin">
                    </div>
                    <div class="input-box">
                        <span class="Registered">註冊日期</span>
                        <input type="date" id="Registered" name="Registered" value="2023-04-27" asp-for="A_RegisteredAt">
                    </div>
                    <div class="input-box">
                        <span class="details">裝備</span>
                        <input type="text" placeholder="給他一件裝備" required asp-for="P_id">
                    </div>


                </div>
                <div class="gender-details">
                    @*Gender這個功能還有點問題*@
                    <input type="radio" asp-for="A_Gender" id="dot-1" value="@((int)Gender.男)" checked="@((Model?.A_Gender == Gender.男) ? "checked" : null)">
                    <input type="radio" asp-for="A_Gender" id="dot-2" value="@((int)Gender.女)" checked="@((Model?.A_Gender == Gender.女) ? "checked" : null)">
                    <input type="radio" asp-for="A_Gender" id="dot-3" value="@((int)Gender.其他)" checked="@((Model?.A_Gender == Gender.其他) ? "checked" : null)">
                    <span asp-validation-for="A_Gender" class="text-danger"></span>
                    <span class="gender-title">性別</span>
                    <div class="category">
                        <label for="dot-1">
                            <span class="dot one"></span>
                            <span class="gender">男性</span>
                        </label>
                        <label for="dot-2">
                            <span class="dot two"></span>
                            <span class="gender">女性</span>
                        </label>
                        <label for="dot-3">
                            <span class="dot three"></span>
                            <span class="gender">不方便透漏</span>
                        </label>
                    </div>
                </div>
                <div class="button">
                    <input type="submit" value="儲存">
                </div>
                <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Account_Home">刪除</button>
                <a asp-area="Account" asp-controller="Account_Home" asp-action="Index" asp-route-id="" class="btn"><i class=" fa fa-sharp fa-solid fa-arrow-left"></i>回上一頁</a>
            </form>
        </div>
    </div>
</body>



@section Script{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ChickenLive/final_repo_test/final_repo_test/Areas/Account/Views/Account_Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<ClassLibrary.Models.UserAccount>
@{
    ViewData["Title"] = "Account";
    Layout = "_Layout";
    
}
@section Styles{
    <link href="~/css/Accountstyle/style2.css" rel="stylesheet" />
}





<body>
    <div class="container">
        <div class="content">
            <div class="content-2">
                <div class="acount">
                    <div class="title">
                        <h2>會員資料表</h2> 
                        <a asp-area="Account" asp-controller="Account_Home" asp-action="Add" asp-route-id="" class="btn"><i class="fa fa-solid fa-plus"></i> 新增</a>
                    </div>
                    <table>
                        
                        <tr>
                            <th>ID</th>
                            <th>名字</th>
                            <th>使用者名稱</th>
                            <th>性別</th>
                            <th>生日</th>
                            <th>權限</th>
                            <th>option</th>
                        </tr>
                        @foreach (var account in Model)
                        {
                        <tr>
                            <td>@account.A_ID</td>
                            <td>@account.A_Name</td>
                            <td>@account.A_NickName</td>
                            <td>@account.A_Gender</td>
                            <td>@account.Birthday.ToString("yyyy-MM-dd")</td>
                            <td>@account.A_level</td>
                            <td><a href="@Url.Action("Edit", "Account_Home", new { A_Id = account.A_ID })" class="btn"><i class="fa fa-solid fa-eye"></i> View</a></td>
                        </tr>
                        }
                    </table>
                </div>
            </div>
        </div>

    </div>
</body>